config/routes.rb
Musiquemaze::Application.routes.draw do
  resources :posts, :only => [:index, :show]
  

  
  devise_for :users, 
    :path_names => { 
      :sign_in => 'login', 
      :sign_out => 'logout' 
    }, 
    :controllers => { 
      :omniauth_callbacks => "authentications", 
      :sessions => "sessions" 
    } do
      match '/auth/facebook/logout' => 'sessions#facebook_logout', :as => :facebook_logout 
      match 'logout' => 'sessions#destroy', :as => :purge_user_session
    end
    
  resources :contacts, :only => [:create]
  resources :quizzes, :only => [:show] do 
    get 'search', :on => :collection
  end
  
  namespace :admin do 
    resources :posts do
      put 'publish', :on => :member
      put 'unpublish', :on => :member 
    end
    resources :seeders, :except => [:new, :edit]
    resources :categories
    resources :testimonials
    resources :quizzes do
      resources :questions, :shallow => true do
        resources :answers
        resources :clues, :shallow => true
      end
    end
    root :to => "categories#index"
  end

  match 'faq' => 'main#faq', :as => :faq
  match 'copyright' => 'main#copyright', :as => :copyright
  match 'policy' => 'main#policy', :as => :policy
  match 'contactus' => 'main#contactus', :as => :contactus
  match 'about' => 'main#about', :as => :about
  match 'terms' => 'main#terms', :as => :terms
  match 'testimonial' => 'main#testimonial', :as => :testimonial

  root :to => "main#index"

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/models/seeder.rb
class Seeder < ActiveRecord::Base
  belongs_to :seedable, :polymorphic => true
  has_attached_file :doc,
    :path => ":rails_root/public/system/:attachment/:id/:filename",
    :url => "/system/:attachment/:id/:filename"
validates_attachment_presence :doc
  attr_accessible :doc
end

app/controllers/admin/seeders_controller.rb
class Admin::SeedersController < Admin::BaseController
  def index
    @seeders = Seeder.all
  end

  def show
    @seeder = Seeder.find(params[:id])
  end

  def new
    @seeder = Seeder.new
  end

  def create
    @seeder = Seeder.new(params[:seeder])
    if @seeder.save
      if params[:quiz_id].blank?
        redirect_to new_admin_quiz_url(:seeder_id => @seeder.id)
      else
        redirect_to edit_admin_quiz_url(params[:quiz_id], :seeder_id => @seeder.id)
      end
    else
      @quiz_id = params[:quiz_id]
      render :action => 'new'
    end
  end

  def edit
    @seeder = Seeder.find(params[:id])
  end

  def update
    @seeder = Seeder.find(params[:id])
    if @seeder.update_attributes(params[:seeder])
      if params[:quiz_id].blank?
        redirect_to new_admin_quiz_url(:seeder_id => @seeder.id)
      else
        redirect_to edit_admin_quiz_url(params[:quiz_id], :seeder_id => @seeder.id)
      end
    else
      render :action => 'edit'
    end
  end

  def destroy
    @seeder = Seeder.find(params[:id])
    @seeder.destroy
    redirect_to admin_seeders_url, :notice => "Successfully destroyed seeder."
  end
end

app/views/admin/seeders/_form.html.erb
<%= form_for [:admin, @seeder], :html => { :multipart => true } do |f| %>
  <%= f.error_messages %>
  <%= hidden_field_tag "quiz_id", @quiz_id %>
  <p>
    <%= f.label :doc, "Upload File" %><br />
    <%= f.file_field :doc %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/admin/seeders/edit.html.erb
<% title "Edit Seeder" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @seeder %> |
  <%= link_to "View All", admin_seeders_path %>
</p>

app/views/admin/seeders/index.html.erb
<% title "Seeders" %>

<table>
  <tr>
    <th>Doc File Name</th>
    <th>Doc File Size</th>
  </tr>
  <% for seeder in @seeders %>
    <tr>
      <td><%= seeder.doc_file_name %></td>
      <td><%= seeder.doc_file_size %></td>
      <td><%= link_to "Destroy", [:admin, seeder], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/admin/seeders/new.html.erb
<% title "New Seeder" %>

<%= render 'form' %>

<p><%= link_to "Back to List", admin_seeders_path %></p>

app/views/admin/seeders/show.html.erb
<% title "Seeder" %>

<p>
  <strong>Doc File Name:</strong>
  <%= @seeder.doc_file_name %>
</p>
<p>
  <strong>Doc File Size:</strong>
  <%= @seeder.doc_file_size %>
</p>

<p>
  <%= link_to "Edit", edit_admin_seeder_path(@seeder) %> |
  <%= link_to "Destroy", [:admin, @seeder], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", admin_seeders_path %>
</p>