config/routes.rb
Musiquemaze::Application.routes.draw do
  resources :posts, :only => [:index, :show]
  

  
  devise_for :users, 
    :path_names => { 
      :sign_in => 'login', 
      :sign_out => 'logout' 
    }, 
    :controllers => { 
      :omniauth_callbacks => "authentications", 
      :sessions => "sessions" 
    } do
      match '/auth/facebook/logout' => 'sessions#facebook_logout', :as => :facebook_logout 
      match 'logout' => 'sessions#destroy', :as => :purge_user_session
    end
    
  resources :contacts, :only => [:create]
  resources :quizzes, :only => [:show] do 
    get 'search', :on => :collection
  end
  
  namespace :admin do 
    resources :posts do
      put 'publish', :on => :member
      put 'unpublish', :on => :member 
    end
    resources :seeders, :except => [:new, :edit]
    resources :categories
    resources :testimonials
    resources :quizzes do
      resources :questions, :shallow => true do
        resources :answers
        resources :clues, :shallow => true
      end
    end
    root :to => "categories#index"
  end

  match 'faq' => 'main#faq', :as => :faq
  match 'copyright' => 'main#copyright', :as => :copyright
  match 'policy' => 'main#policy', :as => :policy
  match 'contactus' => 'main#contactus', :as => :contactus
  match 'about' => 'main#about', :as => :about
  match 'terms' => 'main#terms', :as => :terms
  match 'testimonial' => 'main#testimonial', :as => :testimonial

  root :to => "main#index"

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :column
  validates :content, :presence => true
  validates :points, :presence => true
  validates :points, :numericality => true
  validates :question_id, :presence => true
  validate :check_primary_answer
  
  attr_accessible :content, :question_id, :primary, :column_id, :points
  
  before_save :set_primary_answer
  
  private
  def check_primary_answer
    pa = self.question.answers.where(:primary => true, :column_id => self.column_id).first if self.question
    if self.primary and pa and pa.id != self.id 
      errors.add(:primary, "There can be only one")  
    end
  end
  
  def set_primary_answer
    unless self.question.answers.where(:primary => true, :column_id => self.column_id).first
      self.primary = true
    end
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_filter :load_question, :only => [:index, :new, :create]

  def index
  end
  
  def show
    @answer = Answer.find(params[:id])
  end

  def new
    @answer = @question.answers.build(params[:answer])
  end

  def create
    @answer = @question.answers.build(params[:answer])
    if @answer.save
      redirect_to admin_question_answers_url(@question), :notice => "Successfully created answer."
    else
      render :action => 'new'
    end
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update_attributes(params[:answer])
      redirect_to admin_question_answers_url(@answer.question), :notice  => "Successfully updated answer."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to admin_question_answers_url(@answer.question), :notice => "Successfully destroyed answer."
  end
  
  private 
  def load_question
    @question = Question.find(params[:question_id])
    @answers = @question.answers.paginate(:per_page => 20, :page => params[:page])
  end
end

app/views/admin/answers/_form.html.erb
<%= f.error_messages %>
<p>
  <%= f.label :content %><br />
  <%= f.text_field :content %>
</p>
<p>
  <%= f.label :points %><br />
  <%= f.text_field :points %>
</p>
<p>
  <%= f.label :primary, "Primary Answer?" %><br />
  <%= check_box("answer", "primary")%>
</p>
<p>
  <%= f.submit :class => "btn" %>
  <%= link_to "Back to Question", admin_question_path(@question), :class => "btn" %>
</p>

app/views/admin/answers/edit.html.erb
<% title "Edit Answer" %>

<%= form_for [:admin, @answer] do |f| %>
<%= render 'form', :f => f %>
<% end %>

app/views/admin/answers/index.html.erb
<% title "Answers" %>

<table class="zebra" cellpadding="0" cellspacing="0">
  <tr>
    <th>Content</th>
    <th>Column</th>
    <th>Primary</th>
    <th colspan="2"></th>
  </tr>
  <% for answer in @answers %>
    <tr>
      <td><%= link_to answer.content, [:admin, answer] %></td>
      <td><%= answer.column.name if answer.column %></td>
      <td><%= answer.primary ? "yes" : "" %></td>
      <td><%= link_to "Edit", edit_admin_answer_path(answer) %></td>
      <td><%= link_to "Destroy", [:admin, answer], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<%= will_paginate @answers %>

<p>
  <%= link_to "New Answer", new_admin_question_answer_path(@question), :class => "btn" %> 
  <%= link_to "Back to Quizzes", admin_quiz_questions_path(@question.quiz), :class => "btn" %>
</p>

app/views/admin/answers/new.html.erb
<% title "New Answer for #{@question.quiz.content}" %>

<%= form_for [:admin, @question, @answer]  do |f| %>
  <%= render 'form', :f => f %>
<% end %>

app/views/admin/answers/show.html.erb
<% title "Answer" %>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>
<p>
  <strong>Quiz:</strong>
  <%= @answer.question.quiz.content if @answer.question.quiz %>
</p>

<p>
  <%= link_to "Edit", edit_admin_answer_path(@answer) %> |
  <%= link_to "Destroy", [:admin, @answer], :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Question", admin_question_path(@answer.question) %>
</p>