config/routes.rb
Musiquemaze::Application.routes.draw do
  resources :posts, :only => [:index, :show]
  

  
  devise_for :users, 
    :path_names => { 
      :sign_in => 'login', 
      :sign_out => 'logout' 
    }, 
    :controllers => { 
      :omniauth_callbacks => "authentications", 
      :sessions => "sessions" 
    } do
      match '/auth/facebook/logout' => 'sessions#facebook_logout', :as => :facebook_logout 
      match 'logout' => 'sessions#destroy', :as => :purge_user_session
    end
    
  resources :contacts, :only => [:create]
  resources :quizzes, :only => [:show] do 
    get 'search', :on => :collection
  end
  
  namespace :admin do 
    resources :posts do
      put 'publish', :on => :member
      put 'unpublish', :on => :member 
    end
    resources :seeders, :except => [:new, :edit]
    resources :categories
    resources :testimonials
    resources :quizzes do
      resources :questions, :shallow => true do
        resources :answers
        resources :clues, :shallow => true
      end
    end
    root :to => "categories#index"
  end

  match 'faq' => 'main#faq', :as => :faq
  match 'copyright' => 'main#copyright', :as => :copyright
  match 'policy' => 'main#policy', :as => :policy
  match 'contactus' => 'main#contactus', :as => :contactus
  match 'about' => 'main#about', :as => :about
  match 'terms' => 'main#terms', :as => :terms
  match 'testimonial' => 'main#testimonial', :as => :testimonial

  root :to => "main#index"

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :quizzes, :dependent => :destroy
  has_one :seeder, :as => :seederable
  validates :name, :presence => true
  validates :name, :uniqueness => true
  
  attr_accessible :name, :published
  
  scope :published, lambda { where(:published => true) }
  scope :unpublished, lambda { where(:published => false) }
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_filter :load_category, :only => [:show, :edit, :update, :destroy]
  
  def index
    @categories = Category.paginate(:page => params[:page], :per_page => 30)
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to [:admin, @category], :notice => "Successfully created category."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(params[:category])
      redirect_to [:admin, @category], :notice  => "Successfully updated category."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_url, :notice => "Successfully destroyed category."
  end
  
  private
  def load_category
    @category = Category.find(params[:id])
  end
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :published %><br />
    <%= f.check_box :published %>
  </p>
  <p><%= f.submit :class => "btn" %> <%= link_to "Back to List", admin_categories_path, :class => "btn" %></p>
<% end %>

app/views/admin/categories/edit.html.erb
<% title "Edit Category" %>

<%= render 'form' %>

app/views/admin/categories/index.html.erb
<% title "Categories" %>

<table class="zebra" cellpadding="0" cellspacing="0">
  <tr>
    <th>Name</th>
    <th>Published</th>
    <th colspan="2"></th>
  </tr>
  <% for category in @categories %>
    <tr>
      <td><%= link_to category.name, [:admin, category] %></td>
      <td><%= category.published? ? "yes" : "no" %></td>
      <td><%= link_to "Edit", edit_admin_category_path(category) %></td>
      <td><%= link_to "Destroy", [:admin, category], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<%= will_paginate @categories %>

<p><%= link_to "New Category", new_admin_category_path, :class => "btn" %></p>

app/views/admin/categories/new.html.erb
<% title "New Category" %>

<%= render 'form' %>

app/views/admin/categories/show.html.erb
<% title "Category" %>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<p>
  <strong>Published:</strong>
  <%= @category.published %>
</p>

<p>
  <%= link_to "Edit", edit_admin_category_path(@category), :class => "btn" %>
  <%= link_to "Destroy", [:admin, @category], :confirm => 'Are you sure?', :method => :delete, :class => "btn" %>
  <%= link_to "View All", admin_categories_path, :class => "btn" %>
</p>