config/routes.rb
Musiquemaze::Application.routes.draw do
  resources :posts, :only => [:index, :show]
  

  
  devise_for :users, 
    :path_names => { 
      :sign_in => 'login', 
      :sign_out => 'logout' 
    }, 
    :controllers => { 
      :omniauth_callbacks => "authentications", 
      :sessions => "sessions" 
    } do
      match '/auth/facebook/logout' => 'sessions#facebook_logout', :as => :facebook_logout 
      match 'logout' => 'sessions#destroy', :as => :purge_user_session
    end
    
  resources :contacts, :only => [:create]
  resources :quizzes, :only => [:show] do 
    get 'search', :on => :collection
  end
  
  namespace :admin do 
    resources :posts do
      put 'publish', :on => :member
      put 'unpublish', :on => :member 
    end
    resources :seeders, :except => [:new, :edit]
    resources :categories
    resources :testimonials
    resources :quizzes do
      resources :questions, :shallow => true do
        resources :answers
        resources :clues, :shallow => true
      end
    end
    root :to => "categories#index"
  end

  match 'faq' => 'main#faq', :as => :faq
  match 'copyright' => 'main#copyright', :as => :copyright
  match 'policy' => 'main#policy', :as => :policy
  match 'contactus' => 'main#contactus', :as => :contactus
  match 'about' => 'main#about', :as => :about
  match 'terms' => 'main#terms', :as => :terms
  match 'testimonial' => 'main#testimonial', :as => :testimonial

  root :to => "main#index"

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/views/admin/shared/_admin_menu.html.erb
<% if user_signed_in? %>
<div class="admin-menu">
  <ul>
    <li><%= link_to "Categories", admin_categories_url -%></li>
    <li><%= link_to "Quizzes", admin_quizzes_url -%></li>
    <li><%= link_to "Seeders", admin_seeders_url -%></li>
    <li><%= link_to "Testimonials", admin_testimonials_url -%></li>
    <li><%= link_to "Posts", admin_posts_url -%></li>
  </ul>
  <div style="float:right;">
    <% if facebook_logged_in? %>
      <%= link_to('Logout', facebook_logout_path, :class => "logout-link") -%>
    <% else %>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => "logout-link") -%>
    <% end %>
  </div>
  <div class="clear"></div>
</div>
<% end %>